module.exports = {
    english: {
        "site-logo-text": "Socializer",
        "sign-in-button-text": "Sign in",
        "main-page-headline": "Welcome to the evolution of social networking",
        "main-page-subheadline": "Interconnect with millions on the hottest networking platform on earth",
        "create-profile-button-text": "Create Your Profile",
        "site-footer-copy-right": "Copyright © Socializer.com 2017.",
        "section-one-text": {
            "part-1": "Make new friends and memories, connect with social groups that share your common interests, showcase",
            "blue-bolded-text": "your life",
            "part-2": "to the world by",
            "bolded-text-1": "uploading photos",
            "part-3": "and",
            "bolded-text-2": "videos",
            "part-4": "With the Socializer community, the world is at",
            "bolded-text-3": "your fingertips",
            "part-5": "Join now and become a part of what has everyone talking."
        },
        "remember-me": "remember me",
        "reset-password": "reset password",
        "email-field-text": "Username or email address",
        "password-field-text": "Password",
        "help-text": "Help",
        "settings-text": "Settings",
        "log-out-text": "Log out",
        "view-profile": "View profile",
        "friends": "Friends",
        "groups": "Groups",
        "home": "Home",
        "messages": "Messages",
        "notifications": "Notifications",
        "like": "Like",
        "comment": "Comment",
        "share": "Share",
        "search": "Search",
        "input-message-box": "What's on your mind?",
        "dislike": "Dislike",
        "socializer-group-box": "Your Socializer Groups",
        "refresh": "Refresh",
        "view-all": "View all",
        "see-more": "See more",
        "show-all": "Show all",
        "people-you-may-know": "People you may know",
        "add-friend": "Add friend",
        "join-group": "Join group"
    },
    spanish: {
        "site-logo-text": "Socializer",
        "sign-in-button-text": "Registrarse",
        "main-page-headline": "Bienvenidos a la evolución de las redes sociales",
        "main-page-subheadline": "Interconectarse con millones en la plataforma de redes más caliente de la tierra",
        "create-profile-button-text": "Crea Tu Perfil",
        "site-footer-copy-right": "Copyright © Socializer.com 2017.",
        "section-one-text": {
            "part-1": "Hacer nuevos amigos y recuerdos, conectar con grupos sociales que comparten sus intereses comunes, mostra",
            "blue-bolded-text": "tu vida",
            "part-2": "al mundo entero por",
            "bolded-text-1": "cargando fotos",
            "part-3": "y",
            "bolded-text-2": "videos",
            "part-4": "Con la comunidad Socializer, el mundo está",
            "bolded-text-3": "en las puntas de tus dedos",
            "part-5": "Únete ahora y hazte parte de esta comunidad grande."
        },
        "remember-me": "recuérdame",
        "reset-password": "restablecer la contraseña",
        "email-field-text": "Nombre de usuario o dirección de correo electrónico",
        "password-field-text": "Contraseña",
        "help-text": "Ayuda",
        "settings-text": "Configuracion",
        "log-out-text": "Salir",
        "view-profile": "Ver perfil",
        "friends": "Amigos",
        "groups": "Groupos",
        "home": "Inicio",
        "messages": "Mensajes",
        "notifications": "Notificaciones",
        "like": "Me gusta",
        "comment": "Comentar",
        "share": "Compartir",
        "search": "Buscar",
        "input-message-box": "Que estas pensando?",
        "dislike": "No me gusta",
        "socializer-group-box": "Tus Groupos Socializer",
        "refresh": "Refrescar",
        "view-all": "Ver todo",
        "see-more": "Ver mas",
        "show-all": "Mostrar todo",
        "people-you-may-know": "Los Conoces?",
        "add-friend": "Añadir amigo",
        "join-group": "Unirse al grupo"
    }
};